// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: outbox_events.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingOutboxEvents = `-- name: ClaimPendingOutboxEvents :many
UPDATE outbox_events
SET next_attempt_at = $2, updated_at = CURRENT_TIMESTAMP
WHERE outbox_id IN (
    SELECT outbox_id
    FROM outbox_events
    WHERE status = 'pending' AND next_attempt_at <= CURRENT_TIMESTAMP
    ORDER BY outbox_id
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING outbox_id, topic, event_key, payload, status, attempts, next_attempt_at, created_at, updated_at
`

type ClaimPendingOutboxEventsParams struct {
	Limit         int32     `json:"limit"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
}

// ClaimPendingOutboxEvents: Atomically claims up to $1 pending events whose retry
// window has elapsed. The claim extends next_attempt_at to $2 (the lease expiry)
// so concurrent relay instances can never publish the same event twice; a crashed
// worker's claim simply expires when the lease passes and the event is retried.
func (q *Queries) ClaimPendingOutboxEvents(ctx context.Context, arg ClaimPendingOutboxEventsParams) ([]*OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimPendingOutboxEvents, arg.Limit, arg.NextAttemptAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.OutboxID,
			&i.Topic,
			&i.EventKey,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (topic, event_key, payload, status, next_attempt_at)
VALUES ($1, $2, $3, 'pending', CURRENT_TIMESTAMP)
RETURNING outbox_id, topic, event_key, payload, status, attempts, next_attempt_at, created_at, updated_at
`

type CreateOutboxEventParams struct {
	Topic    string `json:"topic"`
	EventKey string `json:"event_key"`
	Payload  []byte `json:"payload"`
}

// CreateOutboxEvent: Inserts a pending outbox event for durable Kafka publish.
func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (*OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent, arg.Topic, arg.EventKey, arg.Payload)
	var i OutboxEvent
	err := row.Scan(
		&i.OutboxID,
		&i.Topic,
		&i.EventKey,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteOldOutboxEvents = `-- name: DeleteOldOutboxEvents :execrows
DELETE FROM outbox_events
WHERE status IN ('delivered', 'dead')
  AND updated_at < $1
`

// DeleteOldOutboxEvents: Purges delivered/dead events older than the cutoff.
func (q *Queries) DeleteOldOutboxEvents(ctx context.Context, updatedAt pgtype.Timestamp) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldOutboxEvents, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT outbox_id, topic, event_key, payload, status, attempts, next_attempt_at, created_at, updated_at
FROM outbox_events
WHERE status = 'pending' AND next_attempt_at <= CURRENT_TIMESTAMP
ORDER BY outbox_id
LIMIT $1
`

// GetPendingOutboxEvents: Returns pending events whose retry window has elapsed.
func (q *Queries) GetPendingOutboxEvents(ctx context.Context, limit int32) ([]*OutboxEvent, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.OutboxID,
			&i.Topic,
			&i.EventKey,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventDead = `-- name: MarkOutboxEventDead :one
UPDATE outbox_events
SET status = 'dead', updated_at = CURRENT_TIMESTAMP
WHERE outbox_id = $1 AND status = 'pending'
RETURNING outbox_id, topic, event_key, payload, status, attempts, next_attempt_at, created_at, updated_at
`

// MarkOutboxEventDead: Marks a pending event as dead after exhausting retries.
func (q *Queries) MarkOutboxEventDead(ctx context.Context, outboxID int64) (*OutboxEvent, error) {
	row := q.db.QueryRow(ctx, markOutboxEventDead, outboxID)
	var i OutboxEvent
	err := row.Scan(
		&i.OutboxID,
		&i.Topic,
		&i.EventKey,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const markOutboxEventDelivered = `-- name: MarkOutboxEventDelivered :one
UPDATE outbox_events
SET status = 'delivered', updated_at = CURRENT_TIMESTAMP
WHERE outbox_id = $1 AND status = 'pending'
RETURNING outbox_id, topic, event_key, payload, status, attempts, next_attempt_at, created_at, updated_at
`

// MarkOutboxEventDelivered: Marks a pending event as delivered.
func (q *Queries) MarkOutboxEventDelivered(ctx context.Context, outboxID int64) (*OutboxEvent, error) {
	row := q.db.QueryRow(ctx, markOutboxEventDelivered, outboxID)
	var i OutboxEvent
	err := row.Scan(
		&i.OutboxID,
		&i.Topic,
		&i.EventKey,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :one
UPDATE outbox_events
SET attempts = attempts + 1,
    next_attempt_at = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE outbox_id = $1 AND status = 'pending'
RETURNING outbox_id, topic, event_key, payload, status, attempts, next_attempt_at, created_at, updated_at
`

type MarkOutboxEventFailedParams struct {
	OutboxID      int64     `json:"outbox_id"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
}

// MarkOutboxEventFailed: Increments the attempt counter and schedules the next
// attempt at the provided timestamp (backoff computed by the caller).
func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) (*OutboxEvent, error) {
	row := q.db.QueryRow(ctx, markOutboxEventFailed, arg.OutboxID, arg.NextAttemptAt)
	var i OutboxEvent
	err := row.Scan(
		&i.OutboxID,
		&i.Topic,
		&i.EventKey,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
