// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: merchant_document.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MerchantDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    int32                  `protobuf:"varint,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	MerchantId    int32                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	DocumentType  string                 `protobuf:"bytes,3,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	DocumentUrl   string                 `protobuf:"bytes,4,opt,name=document_url,json=documentUrl,proto3" json:"document_url,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Note          string                 `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	UploadedAt    string                 `protobuf:"bytes,7,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantDocument) Reset() {
	*x = MerchantDocument{}
	mi := &file_merchant_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantDocument) ProtoMessage() {}

func (x *MerchantDocument) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantDocument.ProtoReflect.Descriptor instead.
func (*MerchantDocument) Descriptor() ([]byte, []int) {
	return file_merchant_document_proto_rawDescGZIP(), []int{0}
}

func (x *MerchantDocument) GetDocumentId() int32 {
	if x != nil {
		return x.DocumentId
	}
	return 0
}

func (x *MerchantDocument) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *MerchantDocument) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *MerchantDocument) GetDocumentUrl() string {
	if x != nil {
		return x.DocumentUrl
	}
	return ""
}

func (x *MerchantDocument) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MerchantDocument) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *MerchantDocument) GetUploadedAt() string {
	if x != nil {
		return x.UploadedAt
	}
	return ""
}

func (x *MerchantDocument) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type MerchantDocumentDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	DocumentId    int32                   `protobuf:"varint,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	MerchantId    int32                   `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	DocumentType  string                  `protobuf:"bytes,3,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	DocumentUrl   string                  `protobuf:"bytes,4,opt,name=document_url,json=documentUrl,proto3" json:"document_url,omitempty"`
	Status        string                  `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Note          string                  `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	UploadedAt    string                  `protobuf:"bytes,7,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	UpdatedAt     string                  `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantDocumentDeleteAt) Reset() {
	*x = MerchantDocumentDeleteAt{}
	mi := &file_merchant_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantDocumentDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantDocumentDeleteAt) ProtoMessage() {}

func (x *MerchantDocumentDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantDocumentDeleteAt.ProtoReflect.Descriptor instead.
func (*MerchantDocumentDeleteAt) Descriptor() ([]byte, []int) {
	return file_merchant_document_proto_rawDescGZIP(), []int{1}
}

func (x *MerchantDocumentDeleteAt) GetDocumentId() int32 {
	if x != nil {
		return x.DocumentId
	}
	return 0
}

func (x *MerchantDocumentDeleteAt) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *MerchantDocumentDeleteAt) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *MerchantDocumentDeleteAt) GetDocumentUrl() string {
	if x != nil {
		return x.DocumentUrl
	}
	return ""
}

func (x *MerchantDocumentDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MerchantDocumentDeleteAt) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *MerchantDocumentDeleteAt) GetUploadedAt() string {
	if x != nil {
		return x.UploadedAt
	}
	return ""
}

func (x *MerchantDocumentDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *MerchantDocumentDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type CreateMerchantDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	DocumentType  string                 `protobuf:"bytes,2,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	DocumentUrl   string                 `protobuf:"bytes,3,opt,name=document_url,json=documentUrl,proto3" json:"document_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMerchantDocumentRequest) Reset() {
	*x = CreateMerchantDocumentRequest{}
	mi := &file_merchant_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantDocumentRequest) ProtoMessage() {}

func (x *CreateMerchantDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantDocumentRequest.ProtoReflect.Descriptor instead.
func (*CreateMerchantDocumentRequest) Descriptor() ([]byte, []int) {
	return file_merchant_document_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMerchantDocumentRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *CreateMerchantDocumentRequest) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *CreateMerchantDocumentRequest) GetDocumentUrl() string {
	if x != nil {
		return x.DocumentUrl
	}
	return ""
}

type UpdateMerchantDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    int32                  `protobuf:"varint,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	MerchantId    int32                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	DocumentType  string                 `protobuf:"bytes,3,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	DocumentUrl   string                 `protobuf:"bytes,4,opt,name=document_url,json=documentUrl,proto3" json:"document_url,omitempty"`
	Note          string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMerchantDocumentRequest) Reset() {
	*x = UpdateMerchantDocumentRequest{}
	mi := &file_merchant_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantDocumentRequest) ProtoMessage() {}

func (x *UpdateMerchantDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantDocumentRequest.ProtoReflect.Descriptor instead.
func (*UpdateMerchantDocumentRequest) Descriptor() ([]byte, []int) {
	return file_merchant_document_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMerchantDocumentRequest) GetDocumentId() int32 {
	if x != nil {
		return x.DocumentId
	}
	return 0
}

func (x *UpdateMerchantDocumentRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *UpdateMerchantDocumentRequest) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *UpdateMerchantDocumentRequest) GetDocumentUrl() string {
	if x != nil {
		return x.DocumentUrl
	}
	return ""
}

func (x *UpdateMerchantDocumentRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *UpdateMerchantDocumentRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateMerchantDocumentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    int32                  `protobuf:"varint,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	MerchantId    int32                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMerchantDocumentStatusRequest) Reset() {
	*x = UpdateMerchantDocumentStatusRequest{}
	mi := &file_merchant_document_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantDocumentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantDocumentStatusRequest) ProtoMessage() {}

func (x *UpdateMerchantDocumentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_document_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantDocumentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateMerchantDocumentStatusRequest) Descriptor() ([]byte, []int) {
	return file_merchant_document_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMerchantDocumentStatusRequest) GetDocumentId() int32 {
	if x != nil {
		return x.DocumentId
	}
	return 0
}

func (x *UpdateMerchantDocumentStatusRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *UpdateMerchantDocumentStatusRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *UpdateMerchantDocumentStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type FindMerchantDocumentByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    int32                  `protobuf:"varint,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMerchantDocumentByIdRequest) Reset() {
	*x = FindMerchantDocumentByIdRequest{}
	mi := &file_merchant_document_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMerchantDocumentByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMerchantDocumentByIdRequest) ProtoMessage() {}

func (x *FindMerchantDocumentByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_document_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMerchantDocumentByIdRequest.ProtoReflect.Descriptor instead.
func (*FindMerchantDocumentByIdRequest) Descriptor() ([]byte, []int) {
	return file_merchant_document_proto_rawDescGZIP(), []int{5}
}

func (x *FindMerchantDocumentByIdRequest) GetDocumentId() int32 {
	if x != nil {
		return x.DocumentId
	}
	return 0
}

type TrashedMerchantDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    int32                  `protobuf:"varint,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrashedMerchantDocumentRequest) Reset() {
	*x = TrashedMerchantDocumentRequest{}
	mi := &file_merchant_document_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrashedMerchantDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrashedMerchantDocumentRequest) ProtoMessage() {}

func (x *TrashedMerchantDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_document_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrashedMerchantDocumentRequest.ProtoReflect.Descriptor instead.
func (*TrashedMerchantDocumentRequest) Descriptor() ([]byte, []int) {
	return file_merchant_document_proto_rawDescGZIP(), []int{6}
}

func (x *TrashedMerchantDocumentRequest) GetDocumentId() int32 {
	if x != nil {
		return x.DocumentId
	}
	return 0
}

type RestoreMerchantDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    int32                  `protobuf:"varint,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreMerchantDocumentRequest) Reset() {
	*x = RestoreMerchantDocumentRequest{}
	mi := &file_merchant_document_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreMerchantDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreMerchantDocumentRequest) ProtoMessage() {}

func (x *RestoreMerchantDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_document_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreMerchantDocumentRequest.ProtoReflect.Descriptor instead.
func (*RestoreMerchantDocumentRequest) Descriptor() ([]byte, []int) {
	return file_merchant_document_proto_rawDescGZIP(), []int{7}
}

func (x *RestoreMerchantDocumentRequest) GetDocumentId() int32 {
	if x != nil {
		return x.DocumentId
	}
	return 0
}

type DeleteMerchantDocumentPermanentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    int32                  `protobuf:"varint,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMerchantDocumentPermanentRequest) Reset() {
	*x = DeleteMerchantDocumentPermanentRequest{}
	mi := &file_merchant_document_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMerchantDocumentPermanentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMerchantDocumentPermanentRequest) ProtoMessage() {}

func (x *DeleteMerchantDocumentPermanentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_document_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMerchantDocumentPermanentRequest.ProtoReflect.Descriptor instead.
func (*DeleteMerchantDocumentPermanentRequest) Descriptor() ([]byte, []int) {
	return file_merchant_document_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMerchantDocumentPermanentRequest) GetDocumentId() int32 {
	if x != nil {
		return x.DocumentId
	}
	return 0
}

type FindAllMerchantDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllMerchantDocumentsRequest) Reset() {
	*x = FindAllMerchantDocumentsRequest{}
	mi := &file_merchant_document_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllMerchantDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllMerchantDocumentsRequest) ProtoMessage() {}

func (x *FindAllMerchantDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_document_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllMerchantDocumentsRequest.ProtoReflect.Descriptor instead.
func (*FindAllMerchantDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_merchant_document_proto_rawDescGZIP(), []int{9}
}

func (x *FindAllMerchantDocumentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllMerchantDocumentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllMerchantDocumentsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ApiResponseMerchantDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *MerchantDocument      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMerchantDocument) Reset() {
	*x = ApiResponseMerchantDocument{}
	mi := &file_merchant_document_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMerchantDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMerchantDocument) ProtoMessage() {}

func (x *ApiResponseMerchantDocument) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_document_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMerchantDocument.ProtoReflect.Descriptor instead.
func (*ApiResponseMerchantDocument) Descriptor() ([]byte, []int) {
	return file_merchant_document_proto_rawDescGZIP(), []int{10}
}

func (x *ApiResponseMerchantDocument) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMerchantDocument) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseMerchantDocument) GetData() *MerchantDocument {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsesMerchantDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*MerchantDocument    `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesMerchantDocument) Reset() {
	*x = ApiResponsesMerchantDocument{}
	mi := &file_merchant_document_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesMerchantDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesMerchantDocument) ProtoMessage() {}

func (x *ApiResponsesMerchantDocument) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_document_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesMerchantDocument.ProtoReflect.Descriptor instead.
func (*ApiResponsesMerchantDocument) Descriptor() ([]byte, []int) {
	return file_merchant_document_proto_rawDescGZIP(), []int{11}
}

func (x *ApiResponsesMerchantDocument) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesMerchantDocument) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesMerchantDocument) GetData() []*MerchantDocument {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsePaginationMerchantDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*MerchantDocument    `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta        `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationMerchantDocument) Reset() {
	*x = ApiResponsePaginationMerchantDocument{}
	mi := &file_merchant_document_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationMerchantDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationMerchantDocument) ProtoMessage() {}

func (x *ApiResponsePaginationMerchantDocument) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_document_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationMerchantDocument.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationMerchantDocument) Descriptor() ([]byte, []int) {
	return file_merchant_document_proto_rawDescGZIP(), []int{12}
}

func (x *ApiResponsePaginationMerchantDocument) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationMerchantDocument) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationMerchantDocument) GetData() []*MerchantDocument {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationMerchantDocument) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationMerchantDocumentAt struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        string                      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*MerchantDocumentDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta             `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationMerchantDocumentAt) Reset() {
	*x = ApiResponsePaginationMerchantDocumentAt{}
	mi := &file_merchant_document_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationMerchantDocumentAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationMerchantDocumentAt) ProtoMessage() {}

func (x *ApiResponsePaginationMerchantDocumentAt) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_document_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationMerchantDocumentAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationMerchantDocumentAt) Descriptor() ([]byte, []int) {
	return file_merchant_document_proto_rawDescGZIP(), []int{13}
}

func (x *ApiResponsePaginationMerchantDocumentAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationMerchantDocumentAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationMerchantDocumentAt) GetData() []*MerchantDocumentDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationMerchantDocumentAt) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponseMerchantDocumentDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMerchantDocumentDelete) Reset() {
	*x = ApiResponseMerchantDocumentDelete{}
	mi := &file_merchant_document_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMerchantDocumentDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMerchantDocumentDelete) ProtoMessage() {}

func (x *ApiResponseMerchantDocumentDelete) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_document_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMerchantDocumentDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseMerchantDocumentDelete) Descriptor() ([]byte, []int) {
	return file_merchant_document_proto_rawDescGZIP(), []int{14}
}

func (x *ApiResponseMerchantDocumentDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMerchantDocumentDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseMerchantDocumentAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMerchantDocumentAll) Reset() {
	*x = ApiResponseMerchantDocumentAll{}
	mi := &file_merchant_document_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMerchantDocumentAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMerchantDocumentAll) ProtoMessage() {}

func (x *ApiResponseMerchantDocumentAll) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_document_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMerchantDocumentAll.ProtoReflect.Descriptor instead.
func (*ApiResponseMerchantDocumentAll) Descriptor() ([]byte, []int) {
	return file_merchant_document_proto_rawDescGZIP(), []int{15}
}

func (x *ApiResponseMerchantDocumentAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMerchantDocumentAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_merchant_document_proto protoreflect.FileDescriptor

const file_merchant_document_proto_rawDesc = "" +
	"\n" +
	"\x17merchant_document.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\tapi.proto\"\x88\x02\n" +
	"\x10MerchantDocument\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\x05R\n" +
	"documentId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\x12#\n" +
	"\rdocument_type\x18\x03 \x01(\tR\fdocumentType\x12!\n" +
	"\fdocument_url\x18\x04 \x01(\tR\vdocumentUrl\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x12\x1f\n" +
	"\vuploaded_at\x18\a \x01(\tR\n" +
	"uploadedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\xcd\x02\n" +
	"\x18MerchantDocumentDeleteAt\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\x05R\n" +
	"documentId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\x12#\n" +
	"\rdocument_type\x18\x03 \x01(\tR\fdocumentType\x12!\n" +
	"\fdocument_url\x18\x04 \x01(\tR\vdocumentUrl\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x12\x1f\n" +
	"\vuploaded_at\x18\a \x01(\tR\n" +
	"uploadedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\t \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"\x88\x01\n" +
	"\x1dCreateMerchantDocumentRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12#\n" +
	"\rdocument_type\x18\x02 \x01(\tR\fdocumentType\x12!\n" +
	"\fdocument_url\x18\x03 \x01(\tR\vdocumentUrl\"\xd5\x01\n" +
	"\x1dUpdateMerchantDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\x05R\n" +
	"documentId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\x12#\n" +
	"\rdocument_type\x18\x03 \x01(\tR\fdocumentType\x12!\n" +
	"\fdocument_url\x18\x04 \x01(\tR\vdocumentUrl\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x93\x01\n" +
	"#UpdateMerchantDocumentStatusRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\x05R\n" +
	"documentId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"B\n" +
	"\x1fFindMerchantDocumentByIdRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\x05R\n" +
	"documentId\"A\n" +
	"\x1eTrashedMerchantDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\x05R\n" +
	"documentId\"A\n" +
	"\x1eRestoreMerchantDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\x05R\n" +
	"documentId\"I\n" +
	"&DeleteMerchantDocumentPermanentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\x05R\n" +
	"documentId\"j\n" +
	"\x1fFindAllMerchantDocumentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"y\n" +
	"\x1bApiResponseMerchantDocument\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.pb.MerchantDocumentR\x04data\"z\n" +
	"\x1cApiResponsesMerchantDocument\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x03(\v2\x14.pb.MerchantDocumentR\x04data\"\xb7\x01\n" +
	"%ApiResponsePaginationMerchantDocument\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x03(\v2\x14.pb.MerchantDocumentR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination\"\xc1\x01\n" +
	"'ApiResponsePaginationMerchantDocumentAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x04data\x18\x03 \x03(\v2\x1c.pb.MerchantDocumentDeleteAtR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination\"U\n" +
	"!ApiResponseMerchantDocumentDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"R\n" +
	"\x1eApiResponseMerchantDocumentAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xbb\b\n" +
	"\x17MerchantDocumentService\x12[\n" +
	"\aFindAll\x12#.pb.FindAllMerchantDocumentsRequest\x1a).pb.ApiResponsePaginationMerchantDocument\"\x00\x12a\n" +
	"\rFindAllActive\x12#.pb.FindAllMerchantDocumentsRequest\x1a).pb.ApiResponsePaginationMerchantDocument\"\x00\x12d\n" +
	"\x0eFindAllTrashed\x12#.pb.FindAllMerchantDocumentsRequest\x1a+.pb.ApiResponsePaginationMerchantDocumentAt\"\x00\x12R\n" +
	"\bFindById\x12#.pb.FindMerchantDocumentByIdRequest\x1a\x1f.pb.ApiResponseMerchantDocument\"\x00\x12N\n" +
	"\x06Create\x12!.pb.CreateMerchantDocumentRequest\x1a\x1f.pb.ApiResponseMerchantDocument\"\x00\x12N\n" +
	"\x06Update\x12!.pb.UpdateMerchantDocumentRequest\x1a\x1f.pb.ApiResponseMerchantDocument\"\x00\x12Z\n" +
	"\fUpdateStatus\x12'.pb.UpdateMerchantDocumentStatusRequest\x1a\x1f.pb.ApiResponseMerchantDocument\"\x00\x12P\n" +
	"\aTrashed\x12\".pb.TrashedMerchantDocumentRequest\x1a\x1f.pb.ApiResponseMerchantDocument\"\x00\x12P\n" +
	"\aRestore\x12\".pb.RestoreMerchantDocumentRequest\x1a\x1f.pb.ApiResponseMerchantDocument\"\x00\x12f\n" +
	"\x0fDeletePermanent\x12*.pb.DeleteMerchantDocumentPermanentRequest\x1a%.pb.ApiResponseMerchantDocumentDelete\"\x00\x12J\n" +
	"\n" +
	"RestoreAll\x12\x16.google.protobuf.Empty\x1a\".pb.ApiResponseMerchantDocumentAll\"\x00\x12R\n" +
	"\x12DeleteAllPermanent\x12\x16.google.protobuf.Empty\x1a\".pb.ApiResponseMerchantDocumentAll\"\x00B8Z6github.com/MamangRust/monolith-point-of-sale-shared/pbb\x06proto3"

var (
	file_merchant_document_proto_rawDescOnce sync.Once
	file_merchant_document_proto_rawDescData []byte
)

func file_merchant_document_proto_rawDescGZIP() []byte {
	file_merchant_document_proto_rawDescOnce.Do(func() {
		file_merchant_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_document_proto_rawDesc), len(file_merchant_document_proto_rawDesc)))
	})
	return file_merchant_document_proto_rawDescData
}

var file_merchant_document_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_merchant_document_proto_goTypes = []any{
	(*MerchantDocument)(nil),                        // 0: pb.MerchantDocument
	(*MerchantDocumentDeleteAt)(nil),                // 1: pb.MerchantDocumentDeleteAt
	(*CreateMerchantDocumentRequest)(nil),           // 2: pb.CreateMerchantDocumentRequest
	(*UpdateMerchantDocumentRequest)(nil),           // 3: pb.UpdateMerchantDocumentRequest
	(*UpdateMerchantDocumentStatusRequest)(nil),     // 4: pb.UpdateMerchantDocumentStatusRequest
	(*FindMerchantDocumentByIdRequest)(nil),         // 5: pb.FindMerchantDocumentByIdRequest
	(*TrashedMerchantDocumentRequest)(nil),          // 6: pb.TrashedMerchantDocumentRequest
	(*RestoreMerchantDocumentRequest)(nil),          // 7: pb.RestoreMerchantDocumentRequest
	(*DeleteMerchantDocumentPermanentRequest)(nil),  // 8: pb.DeleteMerchantDocumentPermanentRequest
	(*FindAllMerchantDocumentsRequest)(nil),         // 9: pb.FindAllMerchantDocumentsRequest
	(*ApiResponseMerchantDocument)(nil),             // 10: pb.ApiResponseMerchantDocument
	(*ApiResponsesMerchantDocument)(nil),            // 11: pb.ApiResponsesMerchantDocument
	(*ApiResponsePaginationMerchantDocument)(nil),   // 12: pb.ApiResponsePaginationMerchantDocument
	(*ApiResponsePaginationMerchantDocumentAt)(nil), // 13: pb.ApiResponsePaginationMerchantDocumentAt
	(*ApiResponseMerchantDocumentDelete)(nil),       // 14: pb.ApiResponseMerchantDocumentDelete
	(*ApiResponseMerchantDocumentAll)(nil),          // 15: pb.ApiResponseMerchantDocumentAll
	(*wrapperspb.StringValue)(nil),                  // 16: google.protobuf.StringValue
	(*PaginationMeta)(nil),                          // 17: pb.PaginationMeta
	(*emptypb.Empty)(nil),                           // 18: google.protobuf.Empty
}
var file_merchant_document_proto_depIdxs = []int32{
	16, // 0: pb.MerchantDocumentDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	0,  // 1: pb.ApiResponseMerchantDocument.data:type_name -> pb.MerchantDocument
	0,  // 2: pb.ApiResponsesMerchantDocument.data:type_name -> pb.MerchantDocument
	0,  // 3: pb.ApiResponsePaginationMerchantDocument.data:type_name -> pb.MerchantDocument
	17, // 4: pb.ApiResponsePaginationMerchantDocument.pagination:type_name -> pb.PaginationMeta
	1,  // 5: pb.ApiResponsePaginationMerchantDocumentAt.data:type_name -> pb.MerchantDocumentDeleteAt
	17, // 6: pb.ApiResponsePaginationMerchantDocumentAt.pagination:type_name -> pb.PaginationMeta
	9,  // 7: pb.MerchantDocumentService.FindAll:input_type -> pb.FindAllMerchantDocumentsRequest
	9,  // 8: pb.MerchantDocumentService.FindAllActive:input_type -> pb.FindAllMerchantDocumentsRequest
	9,  // 9: pb.MerchantDocumentService.FindAllTrashed:input_type -> pb.FindAllMerchantDocumentsRequest
	5,  // 10: pb.MerchantDocumentService.FindById:input_type -> pb.FindMerchantDocumentByIdRequest
	2,  // 11: pb.MerchantDocumentService.Create:input_type -> pb.CreateMerchantDocumentRequest
	3,  // 12: pb.MerchantDocumentService.Update:input_type -> pb.UpdateMerchantDocumentRequest
	4,  // 13: pb.MerchantDocumentService.UpdateStatus:input_type -> pb.UpdateMerchantDocumentStatusRequest
	6,  // 14: pb.MerchantDocumentService.Trashed:input_type -> pb.TrashedMerchantDocumentRequest
	7,  // 15: pb.MerchantDocumentService.Restore:input_type -> pb.RestoreMerchantDocumentRequest
	8,  // 16: pb.MerchantDocumentService.DeletePermanent:input_type -> pb.DeleteMerchantDocumentPermanentRequest
	18, // 17: pb.MerchantDocumentService.RestoreAll:input_type -> google.protobuf.Empty
	18, // 18: pb.MerchantDocumentService.DeleteAllPermanent:input_type -> google.protobuf.Empty
	12, // 19: pb.MerchantDocumentService.FindAll:output_type -> pb.ApiResponsePaginationMerchantDocument
	12, // 20: pb.MerchantDocumentService.FindAllActive:output_type -> pb.ApiResponsePaginationMerchantDocument
	13, // 21: pb.MerchantDocumentService.FindAllTrashed:output_type -> pb.ApiResponsePaginationMerchantDocumentAt
	10, // 22: pb.MerchantDocumentService.FindById:output_type -> pb.ApiResponseMerchantDocument
	10, // 23: pb.MerchantDocumentService.Create:output_type -> pb.ApiResponseMerchantDocument
	10, // 24: pb.MerchantDocumentService.Update:output_type -> pb.ApiResponseMerchantDocument
	10, // 25: pb.MerchantDocumentService.UpdateStatus:output_type -> pb.ApiResponseMerchantDocument
	10, // 26: pb.MerchantDocumentService.Trashed:output_type -> pb.ApiResponseMerchantDocument
	10, // 27: pb.MerchantDocumentService.Restore:output_type -> pb.ApiResponseMerchantDocument
	14, // 28: pb.MerchantDocumentService.DeletePermanent:output_type -> pb.ApiResponseMerchantDocumentDelete
	15, // 29: pb.MerchantDocumentService.RestoreAll:output_type -> pb.ApiResponseMerchantDocumentAll
	15, // 30: pb.MerchantDocumentService.DeleteAllPermanent:output_type -> pb.ApiResponseMerchantDocumentAll
	19, // [19:31] is the sub-list for method output_type
	7,  // [7:19] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_merchant_document_proto_init() }
func file_merchant_document_proto_init() {
	if File_merchant_document_proto != nil {
		return
	}
	file_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_document_proto_rawDesc), len(file_merchant_document_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_document_proto_goTypes,
		DependencyIndexes: file_merchant_document_proto_depIdxs,
		MessageInfos:      file_merchant_document_proto_msgTypes,
	}.Build()
	File_merchant_document_proto = out.File
	file_merchant_document_proto_goTypes = nil
	file_merchant_document_proto_depIdxs = nil
}
