apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: pointofsale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          args:
            - "postgres"
            - "-c"
            - "max_connections=1000"
            - "-c"
            - "shared_buffers=4GB"
            - "-c"
            - "effective_cache_size=12GB"
            - "-c"
            - "maintenance_work_mem=512MB"
            - "-c"
            - "checkpoint_completion_target=0.9"
            - "-c"
            - "wal_buffers=16MB"
            - "-c"
            - "default_statistics_target=100"
            - "-c"
            - "random_page_cost=1.1"
            - "-c"
            - "effective_io_concurrency=200"
            - "-c"
            - "work_mem=32MB"
            - "-c"
            - "min_wal_size=1GB"
            - "-c"
            - "max_wal_size=4GB"
            - "-c"
            - "max_worker_processes=8"
            - "-c"
            - "max_parallel_workers_per_gather=4"
            - "-c"
            - "max_parallel_workers=8"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB
            - name: POSTGRES_INITDB_ARGS
              value: "-E UTF8 --locale=C"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - DRAGON
                - -d
                - POINTOFSALE
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres
